version: '3.8' # Specifies the Docker Compose file format version

services:
  perforce-server:
    # Use the Perforce Helix Core server image from Sourcegraph
    image: sourcegraph/helix-p4d:latest # You can specify a version tag like sourcegraph/helix-p4d:2023.1
    container_name: p4d-server
    # Environment variables for Perforce server configuration
    # Refer to https://github.com/sourcegraph/helix-docker for more options
    environment:
      - P4NAME=p4server_local # Name of the Perforce server instance
      - P4PORT=1666           # Port the Perforce server will listen on inside the container
      - P4USER=super          # Default superuser name
      - P4PASSWD=YourStrongPassword123! # !IMPORTANT! Change this to a strong, unique password
      # - P4CASE=-C1            # Case-sensitivity (C1 for case-insensitive on Windows, C0 for case-sensitive on Linux/macOS)
      # - P4CHARSET=utf8        # Character set
      # - JNL_PREFIX=p4server_local # Journal file prefix
    ports:
      - "1666:1666" # Map host port 1666 to container port 1666
    volumes:
      # Mount a named volume to persist Perforce server data
      # This ensures your data (depots, users, workspaces, etc.) is not lost when the container is removed
      - p4_server_data:/p4 # /p4 is the P4HOME directory inside the container
    restart: unless-stopped # Restart policy for the container
    healthcheck:
      test: ["CMD", "p4", "-p", "localhost:1666", "-u", "super", "info"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - p4_network

  # Node.js API Server for Perforce Integration
  nodejs-api:
    build:
      context: ./nodejs-api
      dockerfile: Dockerfile
    container_name: p4-nodejs-api
    ports:
      - "3000:3000"
    environment:
      - P4PORT=perforce-server:1666
      - P4USER=super
      - P4PASSWD=YourStrongPassword123!
      - P4CLIENT=nodejs-client
      - NODE_ENV=development
    volumes:
      - nodejs-api:/workspace
    networks:
      - p4_network
    depends_on:
      perforce-server:
        condition: service_healthy
    restart: unless-stopped

volumes:
  p4_server_data:
    driver: local
  nodejs-api:
    driver: local

networks:
  p4_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
